### ISSUE TITLE
Preserve formatting if yml already exists

### ISSUE THREAD

**Issue by Gregory108** [Dashlane/dbt-invoke#10]
Running dbt-invoke comes at the price of loosing formatting.
Currently, `dbt-invoke properties` squashes and unindents
```
    - name: X

    - name: Y
 ```

to

```
- name: X
- name: Y
```

Or re-formats lists (e.g. in tests) from 
```
values: ["A", "B"]
```
to 
```
values:
    - "A"
    - "B"
```

Hence there are three options:
- either people have to switch to formatting - compact and rich with hyphens (which is less readable and navigable)
- or we have to redo formatting after every `dbt-invoke properties` (Nope out!=)
- limit the use of `dbt-invoke properties` only to freshly-generated models and update variables list manually (my current approach=/)

Request:
To preserve formatting for pieces of documentation are already written in yml

(PS: how can I contribute?)

**Comment by robastel** [comment]
This would be a nice option if we can make it work.  I would also like to keep the option to reformat to some basic default formatting like we have now.  We use that at Dashlane to make sure our property files are formatted consistently.

It looks like the [ruamel.yaml](https://yaml.readthedocs.io/en/latest/overview.html) package can handle "round-trip" yaml formatting with a few limitations.  We currently use [PyYAML](https://pyyaml.org/wiki/PyYAMLDocumentation) which does not handle "round-trip" formatting as far as I know.

My first idea would be to alter the `parse_yaml` and `write_yaml` functions in [_utils.py](https://github.com/Dashlane/dbt-invoke/blob/8e54944155e3d480e56f7bd56b93f56d3cb0654f/dbt_invoke/internal/_utils.py#L65) to take that into account.  I think we would want to control this behavior by accepting a new command line argument in [properties.py](https://github.com/Dashlane/dbt-invoke/blob/8e54944155e3d480e56f7bd56b93f56d3cb0654f/dbt_invoke/properties.py), but I am open to other thoughts.

I'm glad you would like to contribute! I think the best way go about that process is to:
- Open up an issue like you did here
- Discuss and agree on a design
- Create a fork to implement the design
- Add test(s) if the changes are not covered by an existing test
- Make sure all tests are passing
- Update the [version number](https://github.com/Dashlane/dbt-invoke/blob/main/dbt_invoke/internal/_version.py)
- Submit a pull request

What are your thoughts on of all that?
