### ISSUE TITLE
Bug: properties command fails when dbt issues warning

### ISSUE THREAD

**Issue by ciklista** [Dashlane/dbt-invoke#12]
**Problem:**

` dbt-invoke properties` raises `json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)` when `dbt ls --output json` issues a warning like 

```
08:04:21  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
{"resource_type": "model", "depends_on": {"macros": [], ...
...
```

The issue is in the parsing of the `dbt ls` parsing (https://github.com/Dashlane/dbt-invoke/blob/main/dbt_invoke/internal/_utils.py#L171) which will fail if not all the output is valid json. 

I assume that this might not be the only place where `dbt` json output is being parsed but I haven't had the time to investigate further yet. I think `dbt` will raise the warning on most (if not all) `dbt` commands. 

**Proposed solution**
Imho I think that warnings should be passed onto the output of ` dbt-invoke properties` but should not cause the command to fail.

**Comment by robastel** [comment]
I plan on taking a further look into this and potentially working on a solution in the coming days.
