### ISSUE TITLE
Should `--resource-type` be set for `dbt ls` by default?

### ISSUE THREAD

**Issue by ciklista** [Dashlane/dbt-invoke#18]
When passing additional arguments to `dbt-invoke`, resource types are no longer filtered in the `dbt ls` command. 

https://github.com/Dashlane/dbt-invoke/blob/949c0ebfbf6a0ad01192f225827e8f68ef30b8c2/dbt_invoke/internal/_utils.py#L159-L164

Is this expected behavior?
This will cause `dbt-invoke update --select foo` to fail if unsupported resource types (e.g. tests) are matched for the `--select` string. One would have to append the resource type to the above command in order to avoid getting unsupported types: `dbt-invoke update --select foo --resource-type model`

**Proposed behavior**
I tend to think that `--resource-type` should always be set to the supported ones as long as they are not explicitly passed by the user.

**Comment by robastel** [comment]
I think your proposed behavior is better than the current behavior.  I'll assign this one to myself and create a PR for it.
